name: ci
on:
  push:
    branches:
      - "**"
      - "!master"
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Build shell image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          repository: shell-image
          push: false
          file: ./shell/Dockerfile
      - name: Run tests in shell
        uses: addnab/docker-run-action@v2
        with:
          image: shell-image:latest
          run: /plcc/tests/run
